export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  products: "/products",
  product: (slug: string) => `/products/${slug}`,
  category: (slug: string) => `/categories/${slug}`,
  brand: (slug: string) => `/brands/${slug}`,
  collection: (slug: string) => `/collections/${slug}`,
  search: (q?: string) => (q ? `/search?q=${encodeURIComponent(q)}` : "/search"),
  cart: "/cart",
  checkout: "/checkout",
  checkoutAddress: (id: string) => `/checkout/${id}/address`,
  checkoutPayment: (id: string) => `/checkout/${id}/payment`,
  checkoutConfirm: (id: string) => `/checkout/${id}/confirm`,
  checkoutSuccess: (id: string) => `/checkout/success?session=${id}`,
  account: "/account",
  orders: "/account/orders",
  order: (id: string) => `/account/orders/${id}`,
  wishlist: "/account/wishlist",
  addresses: "/account/addresses",
  settings: "/account/settings",
  notifications: "/account/notifications",
  recommendations: "/recommendations",
  dashboard: "/dashboard",
  adminAnalytics: "/dashboard/analytics",
  adminProducts: "/dashboard/products",
  adminProductNew: "/dashboard/products/new",
  adminProductEdit: (id: string) => `/dashboard/products/${id}/edit`,
  adminOrders: "/dashboard/orders",
  adminCustomers: "/dashboard/customers",
  adminInventory: "/dashboard/inventory",
  adminMarketing: "/dashboard/marketing",
  adminSettings: "/dashboard/settings",
} as const;
