#!/usr/bin/env sh
# .husky/commit-msg => se ejecuta sobre el ARCHIVO TEMPORAL que contiene el mensaje del commit

# pnpm exec commitlint => ejecuta commitlint instalado en node_modules (pnpm en todo el proyecto, reemplaza "npx --no")
# --edit "$1" => "$1" es el path al archivo de mensaje que git le pasa a este hook
pnpm exec commitlint --edit "$1"
